[theme]
base = "dark"
primaryColor = "#800020"
backgroundColor = "#0E1117"         # Dark background
secondaryBackgroundColor = "#262730" # Slightly lighter dark
textColor = "#FAFAFA"               # Light text
font = "sans serif"
